#include <hal.h>

void boardInit(void) {
    rccResetAHB4(STM32_GPIO_EN_MASK);
    rccEnableAHB4(STM32_GPIO_EN_MASK, true);
    palSetLineMode(BOARD_PAL_LINE_CAN1_RX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_CAN1_TX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_CAN1_SLEEP, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_CAN2_SLEEP, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palClearLine(BOARD_PAL_LINE_CAN1_SLEEP);
    palClearLine(BOARD_PAL_LINE_CAN2_SLEEP);

    palSetLineMode(BOARD_PAL_LINE_CAN1_TERMINATE, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_CAN2_TERMINATE, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palClearLine(BOARD_PAL_LINE_CAN1_TERMINATE);
    palClearLine(BOARD_PAL_LINE_CAN2_TERMINATE);

    palSetLineMode(BOARD_PAL_LINE_USART3_TX, PAL_MODE_ALTERNATE(7) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_USART3_RX, PAL_MODE_ALTERNATE(7) | PAL_STM32_OSPEED_HIGHEST);

    palSetLineMode(BOARD_PAL_LINE_SDMMC_D0, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SDMMC_D1, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SDMMC_D2, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SDMMC_D3, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SDMMC_CK, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SDMMC_CMD, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);

    palSetLineMode(BOARD_PAL_LINE_SPI5_SCK, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_LOWEST);
    palSetLineMode(BOARD_PAL_LINE_SPI5_MOSI, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_LOWEST);
    palSetLineMode(BOARD_PAL_LINE_SPI5_MISO, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_LOWEST);

    palSetLineMode(BOARD_PAL_LINE_SPI1_SCK, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SPI1_MOSI, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SPI1_MISO, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_HIGHEST);

    palSetLineMode(BOARD_PAL_LINE_ICM_CS, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palSetLine(BOARD_PAL_LINE_ICM_CS);
}
