#include <hal.h>

void boardInit(void) {
    palSetLineMode(BOARD_PAL_LINE_CAN1_RX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_CAN1_TX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(PAL_LINE(GPIOC, 13), PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(PAL_LINE(GPIOG, 11), PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palClearLine(PAL_LINE(GPIOC, 13));
    palClearLine(PAL_LINE(GPIOG, 11));

    palSetLineMode(BOARD_PAL_LINE_CAN1_TERMINATE, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palSetLine(BOARD_PAL_LINE_CAN1_TERMINATE);

    palSetLineMode(BOARD_PAL_LINE_SDMMC_D0, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SDMMC_D1, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SDMMC_D2, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SDMMC_D3, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SDMMC_CK, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SDMMC_CMD, PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST);

    palSetLineMode(BOARD_PAL_LINE_SPI5_SCK, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_LOWEST);
    palSetLineMode(BOARD_PAL_LINE_SPI5_MOSI, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_LOWEST);
    palSetLineMode(BOARD_PAL_LINE_SPI5_MISO, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_LOWEST);

    palSetLineMode(BOARD_PAL_LINE_SPI1_SCK, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SPI1_MOSI, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SPI1_MISO, PAL_MODE_ALTERNATE(5) | PAL_STM32_OSPEED_HIGHEST);

    palSetLineMode(BOARD_PAL_LINE_ICM_CS, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palSetLine(BOARD_PAL_LINE_ICM_CS);
}

#if HAL_USE_SDC || defined(__DOXYGEN__)
/**
 * @brief   SDC card detection.
 */
bool sdc_lld_is_card_inserted(SDCDriver *sdcp) {

  (void)sdcp;
  /* TODO: Fill the implementation.*/
  return true;
}

/**
 * @brief   SDC card write protection detection.
 */
bool sdc_lld_is_write_protected(SDCDriver *sdcp) {

  (void)sdcp;
  /* TODO: Fill the implementation.*/
  return false;
}
#endif /* HAL_USE_SDC */
